version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: documento
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: documento
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
